type DanbooruPost = {
  approver_id: number | null;
  bit_flags: number;
  created_at: string;
  down_score: number;
  fav_count: number;
  file_ext: string;
  file_size: number;
  file_url: string;
  has_active_children: boolean;
  has_children: boolean;
  has_large: boolean;
  has_visible_children: boolean;
  id: number;
  image_height: number;
  image_width: number;
  is_banned: boolean;
  is_deleted: boolean;
  is_flagged: boolean;
  is_pending: boolean;
  large_file_url: string;
  last_comment_bumped_at: string | null;
  last_commented_at: string | null;
  last_noted_at: string | null;
  md5: string;
  media_asset: {
    created_at: string;
    duration: number | null;
    file_ext: string;
    file_key: string;
    file_size: number;
    id: number;
    image_height: number;
    image_width: number;
    is_public: boolean;
    md5: string;
    pixel_hash: string;
    status: string;
    updated_at: string;
    variants: Array<{
      file_ext: string;
      height: number;
      type: string;
      url: string;
      width: number;
    }>;
  };
  parent_id: number;
  pixiv_id: number | null;
  preview_file_url: string;
  rating: string;
  score: number;
  source: string;
  tag_count: number;
  tag_count_artist: number;
  tag_count_character: number;
  tag_count_copyright: number;
  tag_count_general: number;
  tag_count_meta: number;
  tag_string: string;
  tag_string_artist: string;
  tag_string_character: string;
  tag_string_copyright: string;
  tag_string_general: string;
  tag_string_meta: string;
  up_score: number;
  updated_at: string;
  uploader_id: number;
};

export type { DanbooruPost };
